name: "Newton's Glass"
favicon: null
layout_spectrum: 0.5903803932014853
typography_spectrum: 0.10418208339251578
title: "Newton's Glass"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6950644666794688
  lightness: 0.7343468882609159
  saturation: 0.8705183097627014
  rhythmicContrast: 0.10553376842290163
purpose: []
