name: "Newton's Glass"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66341
title: "Newton's Glass"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090303'
    - '#fdfdfd'
    - '#0046be'
    - '#8d8aff'
    - '#deb380'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
